# Generated by Django 2.1.15 on 2022-11-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='date',
        ),
    ]
