# Generated by Django 2.1.15 on 2022-11-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0002_remove_contactus_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='messsage',
            new_name='message',
        ),
    ]
