# Generated by Django 2.1.15 on 2022-11-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0004_bookticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookticket',
            old_name='bid',
            new_name='id',
        ),
    ]
