# Generated by Django 2.1.15 on 2022-11-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0006_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='id',
            new_name='bid',
        ),
    ]
