# Generated by Django 2.1.15 on 2022-11-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0007_auto_20221129_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='bid',
            new_name='id',
        ),
    ]
