# Generated by Django 2.1.15 on 2022-11-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0008_auto_20221129_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
